sudo: required

services:
  - docker

before_install:
  - docker build -t hmada15/react-dock -f ./front/Dockerfile.dev ./front
  
script:
  - docker run -e CI=true hmada15/react-dock npm test

after_success:
  - docker build -t hmada15/multi-front ./front
  - docker build -t hmada15/multi-api ./api
  - docker build -t hmada15/multi-nginx ./nginx
  - docker build -t hmada15/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  
  - docker push hmada15/multi-front
  - docker push hmada15/multi-api
  - docker push hmada15/multi-nginx
  - docker push hmada15/multi-worker

deploy:
  provider: elasticbeanstalk
  region: $REGION
  app: $APP_NAME
  env: $APP_ENVIRONMENT_NAME
  bucket_name: $BUCKET_NAME
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
